// SPDX-License-Identifier: Apache-2.0

package main

import (
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

// The Update & Backup card shows the GitHub release body verbatim. That body used
// to be generated by generate_release_notes alone, which — because releases are
// pushed straight to main and have no merged PRs to summarise — produced nothing
// but a compare link. The operator was asked to install a build described only by a
// URL. tag-release.yml now lifts the version's own CHANGELOG section into the body.
//
// The failure mode this guards is silent: the release still publishes, the card
// still renders, and only a human reading it notices there is nothing there.

func repoFile(t *testing.T, rel string) string {
	t.Helper()
	b, err := os.ReadFile(filepath.Join("..", "..", filepath.FromSlash(rel)))
	if err != nil {
		t.Fatalf("read %s: %v", rel, err)
	}
	return string(b)
}

// TestThisReleaseHasNotes is the one that matters at release time: bumping the
// version without adding its CHANGELOG section would publish an empty body.
func TestThisReleaseHasNotes(t *testing.T) {
	script := filepath.Join("..", "..", "scripts", "changelog-section.sh")
	if _, err := os.Stat(script); err != nil {
		t.Fatalf("scripts/changelog-section.sh is missing; the release body depends on it: %v", err)
	}
	out, err := exec.Command("bash", script, Version).Output()
	if err != nil {
		t.Fatalf("changelog-section.sh %s: %v", Version, err)
	}
	notes := strings.TrimSpace(string(out))
	if notes == "" {
		t.Fatalf("no release notes for %s", Version)
	}
	// The placeholder means the section was not found — a real section always has
	// at least one bullet.
	if strings.HasPrefix(notes, "See CHANGELOG.md") {
		t.Errorf("CHANGELOG.md has no \"## [%s]\" section, so the release would ship with no description", Version)
	}
	if !strings.Contains(notes, "- ") {
		t.Errorf("release notes for %s carry no bullet points:\n%s", Version, notes)
	}
	// The version heading itself must not be inside the body: the release page and
	// the update card both already show the version.
	if strings.Contains(notes, "## ["+Version+"]") {
		t.Error("the extracted section must not repeat its own version heading")
	}
}

// TestReleaseVersionFilesAgree pins the three files a release must keep in step.
// They are edited by hand, and a mismatch is invisible until the wrong binary is
// published under the right tag.
func TestReleaseVersionFilesAgree(t *testing.T) {
	rv := repoFile(t, ".release-version")
	if rv != "v"+Version {
		t.Errorf(".release-version is %q but main.go Version is %q — the tag and the binary would disagree", rv, Version)
	}
	if !strings.Contains(repoFile(t, "CHANGELOG.md"), "## ["+Version+"]") {
		t.Errorf("CHANGELOG.md has no section for %s", Version)
	}
}

// TestReleaseWorkflowUsesTheExtractedNotes guards the wiring. The script can be
// perfect and the release still ship a bare compare link if the workflow stops
// passing body_path.
func TestReleaseWorkflowUsesTheExtractedNotes(t *testing.T) {
	wf := repoFile(t, ".github/workflows/tag-release.yml")
	if !strings.Contains(wf, "scripts/changelog-section.sh") {
		t.Error("tag-release.yml must extract the CHANGELOG section")
	}
	if !strings.Contains(wf, "body_path: dist/RELEASE_NOTES.md") {
		t.Error("tag-release.yml must publish the extracted notes as the release body")
	}
}

// TestUpdateNotesRenderedWithoutInnerHTML pins the safety property of the summary
// renderer. Release notes are EXTERNAL content fetched from GitHub; the panel's
// whole contract (see its header comment) is that server data never reaches
// innerHTML.
func TestUpdateNotesRenderedWithoutInnerHTML(t *testing.T) {
	js := withoutComments(repoFile(t, "static/js/admin-os-update.js"))
	if strings.Contains(js, "innerHTML") {
		t.Error("the release-notes renderer must build nodes with textContent, never innerHTML")
	}
	for _, want := range []string{"function parseNotes", "function renderNotes", "function splitLead"} {
		if !strings.Contains(js, want) {
			t.Errorf("missing %s — the card would fall back to dumping raw markdown", want)
		}
	}
	// GitHub's generated tail repeats the release name and links away from the page
	// we are trying to make unnecessary.
	if !strings.Contains(js, "Full Changelog") {
		t.Error("the renderer must drop GitHub's generated Full Changelog tail")
	}
}

// TestProvisioningHelperVersionStampIsWired pins a coupling neither side can
// see. provision-subdomains.sh assigns HELPERS_VERSION_STAMP and never reads
// it; tag-release.yml seds that exact line to the release version and greps to
// confirm the stamp landed. shellcheck, reading only the script, calls it unused
// (SC2034) — and it was deleted on that advice, which failed the release at the
// grep. The linter was not wrong about what it could see. This test is what it
// could not see.
func TestProvisioningHelperVersionStampIsWired(t *testing.T) {
	script := repoFile(t, "scripts/provision-subdomains.sh")
	if !strings.Contains(script, "\nHELPERS_VERSION_STAMP=") {
		t.Error("provision-subdomains.sh has no HELPERS_VERSION_STAMP line at the start of a line; " +
			"tag-release.yml's sed anchors on ^HELPERS_VERSION_STAMP= and the release will fail")
	}
	// The disable is load-bearing: without it the now-blocking shell lint
	// rejects the line the release depends on, and the next person deletes it
	// again for the same reason.
	if !strings.Contains(script, "shellcheck disable=SC2034") {
		t.Error("the HELPERS_VERSION_STAMP assignment needs its SC2034 disable, or shell lint fails the build")
	}

	wf := repoFile(t, ".github/workflows/tag-release.yml")
	if !strings.Contains(wf, "^HELPERS_VERSION_STAMP=") {
		t.Error("tag-release.yml no longer rewrites HELPERS_VERSION_STAMP; the shipped helpers would " +
			"stamp themselves \"dev\" and the root worker could not tell an upgrade from a downgrade")
	}
	if !strings.Contains(wf, "the helper version stamp was not applied") {
		t.Error("tag-release.yml must still verify the stamp landed; a sed that silently matches nothing " +
			"publishes helpers stamped \"dev\"")
	}
}

// TestReleaseToolchainIsPinned pins the compiler, which is the last thing
// standing between "our two builds match" and "anyone can rebuild this tag and
// get the published binary".
//
// v3.17.47 was built with go1.26.5 while the workflow asked setup-go for
// "stable" — so the compiler was decided by whatever the runner had that day,
// and nothing in the repository recorded it. Two builds a month apart could
// then differ for a reason no diff shows. tag-release.yml builds with
// GOTOOLCHAIN=auto, so this directive is what actually decides.
//
// It also closed a gap in the other direction: local gates were running
// go1.25.8 against a CI that had moved to 1.26, so "green locally" and "green
// in CI" were statements about different compilers.
func TestReleaseToolchainIsPinned(t *testing.T) {
	mod := repoFile(t, "go.mod")
	if !strings.Contains(mod, "\ntoolchain go1.") {
		t.Fatal("go.mod carries no toolchain directive; the release compiler is then " +
			"whatever the runner happens to have, and the build is not reproducible from the tag")
	}
	// GOTOOLCHAIN=auto is what makes the directive binding rather than advisory.
	wf := repoFile(t, ".github/workflows/tag-release.yml")
	if !strings.Contains(wf, "GOTOOLCHAIN=auto") {
		t.Error("tag-release.yml must build with GOTOOLCHAIN=auto, or the go.mod toolchain " +
			"directive is ignored and the pin means nothing")
	}
}
