package vayutor

// managed.go — a VayuPress-owned tor daemon. When no external tor control port
// is configured or reachable, VayuTor runs its OWN tor as a child process under
// the (unprivileged) service user, with a private DataDirectory, a
// cookie-authenticated unix control socket, and no SOCKS/relay surface. This
// needs only the `tor` binary on PATH — no root, no systemd, no torrc editing,
// no group membership — so VayuTor "just works" after any update (including the
// in-app binary-only self-update) the moment the binary is present. The onions
// are still bound to VayuPress's lifetime: killing this child tears them down.

import (
	"context"
	"errors"
	"net"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"sync"
	"time"
)

// managedBootTimeout bounds how long we wait for our tor child's control socket
// to accept a connection. tor opens the control port early in startup (well
// before full network bootstrap), so this is generous but rarely approached.
const managedBootTimeout = 25 * time.Second

// managedTor supervises the VayuPress-owned tor process.
type managedTor struct {
	binary string // resolved tor executable (from PATH or an explicit path)
	dir    string // writable base dir we fully own, e.g. <data>/tor

	mu    sync.Mutex
	cmd   *exec.Cmd
	alive bool
	last  string // last spawn/boot error, for the admin status line
}

// newManagedTor prepares (but does not start) a managed instance. binary may be
// "" — ensure then reports a clear "tor not installed" error instead of a
// cryptic dial failure.
func newManagedTor(binary, dir string) *managedTor {
	return &managedTor{binary: binary, dir: dir}
}

func (m *managedTor) dataDir() string       { return filepath.Join(m.dir, "data") }
func (m *managedTor) torrcPath() string     { return filepath.Join(m.dir, "torrc") }
func (m *managedTor) controlSocket() string { return filepath.Join(m.dir, "control.sock") }
func (m *managedTor) cookiePath() string    { return filepath.Join(m.dataDir(), "control_auth_cookie") }
func (m *managedTor) logPath() string       { return filepath.Join(m.dir, "tor.log") }

// controlAddr is what dialControl expects for a unix control socket.
func (m *managedTor) controlAddr() string { return "unix:" + m.controlSocket() }

// resolveBinary returns the tor executable, resolving it from PATH the first
// time it is actually needed (and caching the result). Resolving lazily — rather
// than once at process start — means installing tor AFTER VayuPress is already
// running is picked up on the next reconcile, with no restart.
func (m *managedTor) resolveBinary() string {
	m.mu.Lock()
	b := m.binary
	m.mu.Unlock()
	if strings.TrimSpace(b) != "" {
		return b
	}
	p, err := exec.LookPath("tor")
	if err != nil {
		return ""
	}
	m.mu.Lock()
	m.binary = p
	m.mu.Unlock()
	return p
}

// running reports whether our tor child is currently alive.
func (m *managedTor) running() bool {
	m.mu.Lock()
	defer m.mu.Unlock()
	return m.alive
}

// lastError returns the last spawn/boot failure, if any.
func (m *managedTor) lastError() string {
	m.mu.Lock()
	defer m.mu.Unlock()
	return m.last
}

// buildTorrc renders a minimal, onion-services-only tor configuration. No SOCKS
// proxy, no relaying, no exit — this tor exists solely to publish VayuTor's
// onion services and expose a loopback control socket to VayuPress.
func (m *managedTor) buildTorrc() string {
	var b strings.Builder
	b.WriteString("# Generated by VayuTor — do not edit; regenerated on every start.\n")
	b.WriteString("DataDirectory " + m.dataDir() + "\n")
	b.WriteString("ControlPort unix:" + m.controlSocket() + "\n")
	b.WriteString("CookieAuthentication 1\n")
	// Client-only: no SOCKS listener, no relaying, no directory service. Onion
	// service publication does not need any of them.
	b.WriteString("SocksPort 0\n")
	b.WriteString("RunAsDaemon 0\n")
	// Persist tor's notice log so bootstrap/network problems are inspectable.
	b.WriteString("Log notice file " + m.logPath() + "\n")
	return b.String()
}

// ensure starts the tor child if it is not already running and blocks until its
// control socket is reachable (or a timeout). Idempotent: a live child is a
// no-op. It never uses the caller's context for the process lifetime (tor must
// outlive a single reconcile) — ctx only bounds the boot wait.
func (m *managedTor) ensure(ctx context.Context) error {
	if m.running() {
		return nil
	}
	bin := m.resolveBinary()
	if bin == "" {
		return m.fail("tor is not installed on the server — run one command as root to add it: `sudo apt-get install -y tor` (or re-run the VayuPress updater). VayuTor then comes up automatically within a minute; no restart needed")
	}
	// tor refuses to start unless its DataDirectory is private (0700) and owned
	// by the running user. We create it fresh under our own writable tree.
	if err := os.MkdirAll(m.dataDir(), 0o700); err != nil {
		return m.fail("cannot create tor data dir: " + err.Error())
	}
	_ = os.Chmod(m.dataDir(), 0o700)
	// A stale socket from a previous run would make tor fail to bind.
	_ = os.Remove(m.controlSocket())
	if err := os.WriteFile(m.torrcPath(), []byte(m.buildTorrc()), 0o600); err != nil {
		return m.fail("cannot write torrc: " + err.Error())
	}

	// Deliberately NOT exec.CommandContext: the daemon must survive the reconcile
	// context. Its lifetime is managed by stop()/the wait goroutine below.
	cmd := exec.Command(bin, "-f", m.torrcPath()) //nolint:gosec // fixed binary + our own torrc
	// Capture tor's own log to a file so bootstrap/network failures are
	// diagnosable ("why is my onion offline?") instead of being silently
	// discarded. Truncated each start; tor also mirrors this via `Log notice`.
	if lf, lerr := os.OpenFile(m.logPath(), os.O_CREATE|os.O_TRUNC|os.O_WRONLY, 0o600); lerr == nil {
		cmd.Stdout = lf
		cmd.Stderr = lf
	}
	if err := cmd.Start(); err != nil {
		return m.fail("cannot start tor: " + err.Error())
	}
	m.mu.Lock()
	m.cmd = cmd
	m.alive = true
	m.last = ""
	m.mu.Unlock()
	// Reap the child and record when it exits so running() stays accurate and the
	// next reconcile respawns it.
	go func() {
		_ = cmd.Wait()
		m.mu.Lock()
		m.alive = false
		m.mu.Unlock()
	}()

	if err := m.waitControl(ctx); err != nil {
		return m.fail("tor started but control socket never came up: " + err.Error())
	}
	return nil
}

// waitControl polls the control socket until it accepts a connection.
func (m *managedTor) waitControl(ctx context.Context) error {
	deadline := time.Now().Add(managedBootTimeout)
	for {
		if !m.running() {
			return errors.New("tor process exited during startup")
		}
		c, err := net.DialTimeout("unix", m.controlSocket(), time.Second)
		if err == nil {
			_ = c.Close()
			return nil
		}
		if time.Now().After(deadline) {
			return errors.New("timeout")
		}
		select {
		case <-ctx.Done():
			return ctx.Err()
		case <-time.After(250 * time.Millisecond):
		}
	}
}

// stop terminates the tor child (which tears down its onions). Best-effort.
func (m *managedTor) stop() {
	m.mu.Lock()
	cmd := m.cmd
	m.cmd = nil
	m.alive = false
	m.mu.Unlock()
	if cmd != nil && cmd.Process != nil {
		_ = cmd.Process.Kill()
	}
	_ = os.Remove(m.controlSocket())
}

// fail records the latest error for the admin status line and returns it as an
// error whose message the engine surfaces verbatim.
func (m *managedTor) fail(msg string) error {
	m.mu.Lock()
	m.last = msg
	m.mu.Unlock()
	return errors.New("vayutor: " + msg)
}
