CREATE TABLE IF NOT EXISTS email_templates(kind TEXT PRIMARY KEY,subject TEXT NOT NULL DEFAULT '',text_body TEXT NOT NULL DEFAULT '',html_body TEXT NOT NULL DEFAULT '',updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS i18n_messages(lang TEXT NOT NULL,key TEXT NOT NULL,value TEXT NOT NULL DEFAULT '',PRIMARY KEY(lang,key));
