ALTER TABLE article_access ADD COLUMN price_cents INTEGER NOT NULL DEFAULT 0;
CREATE TABLE IF NOT EXISTS article_purchases (id TEXT PRIMARY KEY, email TEXT NOT NULL, slug TEXT NOT NULL, order_ref TEXT NOT NULL DEFAULT '', status TEXT NOT NULL DEFAULT 'pending', created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, paid_at DATETIME, UNIQUE(email, slug));
