-- Migration 106 (up): a tag's posts are counted and listed from article_tags alone. Every count and listing joined each tag row to articles to read the post's status (and, on a multi-domain install, its domain): one random index seek per tagged post, so a large tag's count cost seconds on a cold multi-GB database (johal.in, 2026-10-10: the connector's list_posts for "python" took 6.1 s and its relay answered 502). Each tag row now carries live (the post is published) and domain_id, kept in step by triggers whatever code path writes articles, so a count is an index range and a page reads articles only for the posts it shows. One index serves both: domain_id last keeps the newest-first order for the whole install, and a site's count or page filters it inside the index. On a 234k-post copy with 1.7M tag rows (cold cache) the "python" count fell from 8.7 s to under 60 ms, and a cold boot through this migration was healthy in 9.3 s; the index build and the orphan sweep dominate it, both in proportion to the tag rows. A post deleted from the console or the API left its tag rows behind (neither path removes them); the join hid them, a count from article_tags alone would not, so the delete trigger removes them on every path and the rows already orphaned are removed once here. NOTE: runMigrations executes line-by-line, so keep each statement on ONE line.
CREATE TRIGGER IF NOT EXISTS article_tags_on_delete AFTER DELETE ON articles BEGIN DELETE FROM article_tags WHERE article_id=OLD.id; END;
DELETE FROM article_tags WHERE article_id NOT IN (SELECT id FROM articles);
ALTER TABLE article_tags ADD COLUMN live INTEGER NOT NULL DEFAULT 1;
ALTER TABLE article_tags ADD COLUMN domain_id TEXT NOT NULL DEFAULT '';
UPDATE article_tags SET live=0 WHERE article_id IN (SELECT id FROM articles WHERE COALESCE(status,'published')<>'published');
UPDATE article_tags SET domain_id=(SELECT COALESCE(a.domain_id,'') FROM articles a WHERE a.id=article_tags.article_id) WHERE article_id IN (SELECT id FROM articles WHERE COALESCE(domain_id,'')<>'');
CREATE TRIGGER IF NOT EXISTS article_tags_on_insert AFTER INSERT ON article_tags BEGIN UPDATE article_tags SET live=COALESCE((SELECT COALESCE(a.status,'published')='published' FROM articles a WHERE a.id=NEW.article_id),1), domain_id=COALESCE((SELECT COALESCE(a.domain_id,'') FROM articles a WHERE a.id=NEW.article_id),'') WHERE rowid=NEW.rowid; END;
CREATE TRIGGER IF NOT EXISTS article_tags_on_article_insert AFTER INSERT ON articles BEGIN UPDATE article_tags SET live=(COALESCE(NEW.status,'published')='published'), domain_id=COALESCE(NEW.domain_id,'') WHERE article_id=NEW.id; END;
CREATE TRIGGER IF NOT EXISTS article_tags_on_article_update AFTER UPDATE OF status, domain_id ON articles BEGIN UPDATE article_tags SET live=(COALESCE(NEW.status,'published')='published'), domain_id=COALESCE(NEW.domain_id,'') WHERE article_id=NEW.id; END;
CREATE INDEX IF NOT EXISTS idx_article_tags_live ON article_tags(tag_norm, live, created_at DESC, article_id, domain_id);
